### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by aayushagrawal** [sushant94/connect#2]
1)I have sent you a category list, please implement that as a drop down list in the category section
2) it is not allowing to post event without an input on the event. - it says event cant be blank. Please change that.
3) Please remove the event ending input
4) Picture input for news?
5) Also , please try to input a news, it is not working, displaying that something is wrong with the logs.

**Comment by sushant94** [comment]
c053bdc24ba9d2d94c23a63e0f2dc3c0985b93c6 Fixed.
